Deduplicate `empty.sycl` file
The current setup uses `try_compile` on the source file `empty.sycl`
twice, which leads to the following error when using Ninja, enabling
SYCL, and having the tests enabled:

```
error: sycl/cmake/empty.sycl is defined as an output multiple times
```

This commit takes the path of least resistance and clones the file into
`empty_ubsan.sycl` so that these compile tests no longer collide.